### PR TITLE
[VID] new namespace proof endpoint

### LINKED ISSUE #2458: [VID] update the logic for namespace proof verification
new namespace proof will contain a proof of correct encoding or a proof of incorrect encoding.
namespace verification should decide the case and check the corresponding proof.

Other items
- https://github.com/EspressoSystems/espresso-sequencer/pull/2579#discussion_r1969965954
- https://github.com/EspressoSystems/espresso-sequencer/pull/2579#discussion_r1969621453 (and https://github.com/EspressoSystems/espresso-sequencer/pull/2579#discussion_r1969901340)

Update:
proof of incorrect encoding will be handled in #2865

### PR DESCRIPTION
**Pull request by mrain**
Closes #2458 

### This PR:
update the namespace query endpoint
- everything stays the same in the old version 0.x
- Starting from version 1.0, it's returning a version gated namespace proof.

### This PR does not:
- It doesn't deal with the proof of incorrect encoding.
- Tech debts about NsTable still remain unsolved.

### CODE REVIEW

File: types/src/v0/impls/block/full_payload/ns_proof/advz.rs [hunk 1]
```diff
@@ -0,0 +1,328 @@
+use hotshot_types::{
```
Comment (sveitser) [inline types/src/v0/impls/block/full_payload/ns_proof/advz.rs:1]: It would be a bit easier to review if it was mentioned that this file contains the previous `ns_proof.rs`

File: types/src/v0/impls/block/full_payload/ns_proof/avidm.rs [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+
+        struct BlockInfo {
+            block: Payload,
+            vid_commit: VidCommitment,
+            ns_proofs: Vec<AvidMNsProof>,
+        }
+
+        let blocks: Vec<BlockInfo> = {
+            // compute blocks separately to avoid async error `captured variable
+            // cannot escape `FnMut` closure body` caused by mutable variable `vid`
```
Comment (sveitser) [inline types/src/v0/impls/block/full_payload/ns_proof/avidm.rs:106]: the mutable variable is commented out now though

File: types/src/v0/nsproof.rs [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+use hotshot_types::data::VidCommitment;
+use serde::{Deserialize, Serialize};
+
+use crate::{
+    v0::{NamespaceId, NsIndex, NsPayload, NsTable, Payload, Transaction},
+    v0_1::ADVZNsProof,
+    v0_3::AvidMNsProof,
+};
+
+/// Each variant represents a specific minor version of a namespace proof.
```
Comment (sveitser) [inline types/src/v0/nsproof.rs:11]: What does this "minor" refer to? I thought it's a pretty "major" change to the VID.

**Review by sveitser — APPROVED** [review]
Not really familiar with our VID but looks reasonable to me. Maybe @alxiong or @akonring could also take a look?

File: types/src/v0/nsproof.rs (hunk 3 above)
Comment (mrain) [reply types/src/v0/nsproof.rs]: rephrased in [97a33eb](https://github.com/EspressoSystems/espresso-network/pull/2866/commits/97a33eb2939a5d86c78b7543f1c9145c2a1897f5)

File: types/src/v0/impls/block/full_payload/ns_proof/avidm.rs (hunk 2 above)
Comment (mrain) [reply types/src/v0/impls/block/full_payload/ns_proof/avidm.rs]: restructured in [97a33eb](https://github.com/EspressoSystems/espresso-network/pull/2866/commits/97a33eb2939a5d86c78b7543f1c9145c2a1897f5)

File: types/src/v0/impls/block/full_payload/ns_proof/advz.rs (hunk 1 above)
Comment (mrain) [reply types/src/v0/impls/block/full_payload/ns_proof/advz.rs:3]: added new description here: [67d6095](https://github.com/EspressoSystems/espresso-network/pull/2866/commits/67d6095c3f74bb6a3930790a8bc4e60e5e5bcd50)

File: types/src/v0/impls/block/full_payload/ns_proof/avidm.rs [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+                        Some((ns_payload.export_all_txs(&ns_id), ns_id))
+                    },
+                    Ok(Err(_)) => None,
+                    Err(e) => {
+                        tracing::warn!("error verifying namespace proof: {:?}", e);
+                        None
+                    },
+                }
+            },
+            _ => None,
```
Comment (alxiong) [inline types/src/v0/impls/block/full_payload/ns_proof/avidm.rs:59]: why don't we verify V2?

**Review by alxiong — APPROVED** [review]
I only briefly look at vid namespace logic, I didn't very carefully review, but also don't want to block progress. I'll come back in the future. 

Generally look good.

File: types/src/v0/impls/block/full_payload/ns_proof/avidm.rs (hunk 4 above)
Comment (mrain) [reply types/src/v0/impls/block/full_payload/ns_proof/avidm.rs:59]: We don't have V2. V0 is handled in the advz module.

File: types/src/v0/v0_3/nsproof.rs [hunk 5]
```diff
@@ -0,0 +1,5 @@
+use serde::{Deserialize, Serialize};
+
+/// Re-export the AVID-M namespace proof.
+#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
+pub struct AvidMNsProof(pub(crate) vid::avid_m::proofs::NsProof);
```
[the remark this answers is not in the document]
Comment (mrain) [reply types/src/v0/v0_3/nsproof.rs:5]: This might be unnecessary. Only two functions related to `NsProof` are proof generation and verification. They already have wrapped implementation here.
